In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Save objects
import joblib

In [2]:
df = pd.read_csv("IBM_EmpDataset.csv")

In [3]:
df.drop(columns=["EmployeeNumber"], inplace=True)

In [4]:
# Separate Features and Target
X = df.drop(columns=["Attrition", "Attrition_Flag"])
y = df["Attrition"]

In [5]:
# Identify Numerical and Categorical Columns
numerical_features = X.select_dtypes(include=["int64", "float64"]).columns.tolist()
categorical_features = X.select_dtypes(include=["object"]).columns.tolist()

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

Numerical Features:
['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EnvironmentSatisfaction', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

Categorical Features:
['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus', 'OverTime']

In [6]:
# Encoding
encoder = OneHotEncoder(
    drop="first",
    sparse_output=False,
    handle_unknown="ignore"
)

In [7]:
encoded_array = encoder.fit_transform(X[categorical_features])
encoded_array

array([[0., 1., 0., ..., 0., 1., 1.],
       [1., 0., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.]])

In [8]:
# Create DataFrame
encoded_df = pd.DataFrame(
    encoded_array,
    columns=encoder.get_feature_names_out(categorical_features),
    index=X.index
)

In [9]:
# Remove Original Categorical Columns
X = X.drop(columns=categorical_features)

In [10]:
# Add Encoded Features
X = pd.concat([X, encoded_df], axis=1)

In [11]:
X.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,2,94,3,2,4,5993,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0
1,49,279,8,1,3,61,2,2,2,5130,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
2,37,1373,2,2,4,92,2,1,3,2090,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
3,33,1392,3,4,4,56,3,1,3,2909,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,40,3,1,2,3468,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [12]:
# Encode Target Variable
y = df["Attrition_Flag"]

In [13]:
y.value_counts()

Attrition_Flag
0    1233
1     237
Name: count, dtype: int64

In [14]:
# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

In [15]:
print("Training Data :", X_train.shape)
print("Testing Data :", X_test.shape)

Training Data : (1176, 44)
Testing Data : (294, 44)

In [16]:
# Standard Scaling
scaler = StandardScaler()

In [17]:
X_train[numerical_features] = scaler.fit_transform(
    X_train[numerical_features]
)

In [18]:
X_test[numerical_features] = scaler.transform(
    X_test[numerical_features]
)

In [19]:
X_train.head()

,Age,DailyRate,DistanceFromHome,Education,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyIncome,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1194,1.090194,1.049455,-0.899915,1.064209,-0.658710,-0.908436,1.795282,1.762189,-0.647997,2.026752,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
128,-1.634828,-0.523449,-0.899915,-1.855332,0.260202,1.694111,0.373564,-0.986265,1.153526,-0.864408,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
810,0.981193,-0.992080,-0.777610,-1.855332,-1.577622,-0.662913,0.373564,1.762189,0.252765,2.347706,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
478,-1.307825,-0.453653,0.445433,-1.855332,-0.658710,-1.252169,0.373564,-0.986265,0.252765,-0.956202,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
491,0.654191,0.491086,-0.043784,2.037390,1.179114,0.319180,0.373564,-0.070114,0.252765,-0.185956,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [20]:
joblib.dump(encoder, "onehot_encoder.pkl")
joblib.dump(scaler, "standard_scaler.pkl")
joblib.dump(numerical_features, "numerical_features.pkl")
joblib.dump(categorical_features, "categorical_features.pkl")

['categorical_features.pkl']

In [21]:
X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)

y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

In [22]:
joblib.dump(X_train.columns.tolist(), "model_columns.pkl")

['model_columns.pkl']